name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Charger l'environnement Node.js (NVM)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Naviguer vers le dossier
            cd /home/${{ secrets.USERNAME }}/htdocs/seclinbasketclub.fr
            
            # Vérifier si c'est un dépôt git, sinon l'initialiser
            if [ ! -d ".git" ]; then
              echo "Initialisation du dépôt Git..."
              git init
              git remote add origin https://github.com/noa-panfil/SBC.git
              git fetch
              git reset --hard origin/main
            else
              echo "Pull des modifications..."
              git config --global --add safe.directory "*"
              git fetch origin
              git reset --hard origin/main
            fi
            
            # Installation et Build
            echo "Installation des dépendances..."
            npm install
            
            echo "Construction du projet..."
            npm run build
            
            # Redémarrage (Si PM2 est utilisé sur le serveur)
            if command -v pm2 &> /dev/null; then
                pm2 reload all || pm2 start npm --name "next-app" -- start
            else
                echo "PM2 non trouvé. Assurez-vous que le site Node.js est bien démarré dans CloudPanel."
            fi